package com.lege.android.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lege.android.base.db.BindInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BIND_INFO".
*/
public class BindInfoDao extends AbstractDao<BindInfo, Long> {

    public static final String TABLENAME = "BIND_INFO";

    /**
     * Properties of entity BindInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IsBind = new Property(1, String.class, "isBind", false, "IS_BIND");
        public final static Property IsPrivacy = new Property(2, String.class, "isPrivacy", false, "IS_PRIVACY");
    };


    public BindInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BindInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BIND_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IS_BIND\" TEXT," + // 1: isBind
                "\"IS_PRIVACY\" TEXT);"); // 2: isPrivacy
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BIND_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BindInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String isBind = entity.getIsBind();
        if (isBind != null) {
            stmt.bindString(2, isBind);
        }
 
        String isPrivacy = entity.getIsPrivacy();
        if (isPrivacy != null) {
            stmt.bindString(3, isPrivacy);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BindInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String isBind = entity.getIsBind();
        if (isBind != null) {
            stmt.bindString(2, isBind);
        }
 
        String isPrivacy = entity.getIsPrivacy();
        if (isPrivacy != null) {
            stmt.bindString(3, isPrivacy);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BindInfo readEntity(Cursor cursor, int offset) {
        BindInfo entity = new BindInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // isBind
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // isPrivacy
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BindInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsBind(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsPrivacy(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BindInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BindInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
